# Generated by Django 4.2.23 on 2025-11-07 08:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attorney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bar_number', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('partner', 'Partner'), ('senior', 'Senior Associate'), ('associate', 'Associate'), ('junior', 'Junior Associate')], max_length=20)),
                ('hire_date', models.DateField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('client_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('nonprofit', 'Non-Profit')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_billable', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('billed', 'Billed'), ('reimbursed', 'Reimbursed')], default='pending', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='practice.attorney')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=30, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='practice.client')),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter_number', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('closed', 'Closed'), ('on_hold', 'On Hold')], default='open', max_length=20)),
                ('billing_type', models.CharField(choices=[('hourly', 'Hourly'), ('flat_fee', 'Flat Fee'), ('contingency', 'Contingency'), ('retainer', 'Retainer')], default='hourly', max_length=20)),
                ('flat_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contingency_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('opened_date', models.DateField()),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('assigned_attorneys', models.ManyToManyField(related_name='assigned_matters', to='practice.attorney')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matters', to='practice.client')),
                ('lead_attorney', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_matters', to='practice.attorney')),
            ],
            options={
                'ordering': ['-opened_date'],
            },
        ),
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('default_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('billed', 'Billed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='practice.attorney')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='practice.matter')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='practice.service')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('check', 'Check'), ('wire', 'Wire Transfer'), ('credit_card', 'Credit Card'), ('ach', 'ACH'), ('cash', 'Cash')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='practice.client')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='practice.invoice')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddField(
            model_name='matter',
            name='practice_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matters', to='practice.practicearea'),
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('time', 'Time Entry'), ('expense', 'Expense'), ('adjustment', 'Adjustment')], max_length=20)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='practice.expense')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='practice.invoice')),
                ('time_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='practice.timeentry')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='practice.matter'),
        ),
        migrations.AddField(
            model_name='expense',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='practice.matter'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('brief', 'Brief'), ('motion', 'Motion'), ('correspondence', 'Correspondence'), ('evidence', 'Evidence'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.CharField(max_length=500)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='practice.matter')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to='practice.attorney')),
            ],
            options={
                'ordering': ['-uploaded_date'],
            },
        ),
        migrations.AddField(
            model_name='attorney',
            name='practice_areas',
            field=models.ManyToManyField(related_name='attorneys', to='practice.practicearea'),
        ),
    ]
