# Generated by Django 4.2.23 on 2025-11-07 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading Files'), ('queued', 'Queued for Processing'), ('processing', 'Processing'), ('waiting_input', 'Waiting for User Input'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('render_job_id', models.CharField(blank=True, max_length=100)),
                ('render_service_id', models.CharField(blank=True, max_length=100)),
                ('files_uploaded', models.IntegerField(default=0)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_imported', models.IntegerField(default=0)),
                ('records_skipped', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('error_details', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('yes_no', 'Yes/No'), ('choice', 'Multiple Choice'), ('text', 'Text Input'), ('skip_continue', 'Skip or Continue')], max_length=20)),
                ('question_text', models.TextField()),
                ('context', models.TextField(blank=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('related_entity', models.CharField(blank=True, max_length=50)),
                ('related_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='practice.importjob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('SUCCESS', 'Success'), ('THINKING', 'Claude Thinking'), ('DECISION', 'Claude Decision')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('metadata', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='practice.importjob')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='import_files/%Y/%m/%d/')),
                ('file_type', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(default=0)),
                ('processed', models.BooleanField(default=False)),
                ('records_found', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='practice.importjob')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_column', models.CharField(max_length=100)),
                ('target_model', models.CharField(max_length=50)),
                ('target_field', models.CharField(max_length=50)),
                ('requires_transformation', models.BooleanField(default=False)),
                ('transformation_type', models.CharField(blank=True, max_length=50)),
                ('transformation_details', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='practice.importfile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='practice.importjob')),
            ],
            options={
                'ordering': ['file', 'source_column'],
                'unique_together': {('file', 'source_column')},
            },
        ),
        migrations.CreateModel(
            name='ImportedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('record_id', models.IntegerField()),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_records', to='practice.importjob')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_records', to='practice.importfile')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['model_name', 'record_id'], name='practice_im_model_n_095796_idx')],
            },
        ),
    ]
